-- Supabase/Postgres schema for the public Streamlit sleep diary.
-- Run the complete file in Supabase SQL Editor before public deployment.
-- Public visitors may INSERT a valid diary row, but cannot SELECT or DELETE rows.
-- The researcher dashboard reads rows with SUPABASE_ADMIN_KEY (service role),
-- which must only be stored in Streamlit Secrets.

create table if not exists public.sleep_logs (
  id bigint generated by default as identity primary key,
  member_id text not null,
  name text not null,
  date text not null,
  headphone_min integer not null check (headphone_min >= 0),
  sleep_time text not null,
  sleep_time_ampm text not null check (sleep_time_ampm in ('AM', 'PM')),
  sleep_onset_min integer not null check (sleep_onset_min >= 0),
  wakeup_count integer not null check (wakeup_count >= 0),
  fallback_sleep text not null,
  disturbance text not null,
  disturbance_scale integer not null check (disturbance_scale between 0 and 5),
  morning_wake_time text not null,
  wake_time text not null,
  sleep_quality integer not null check (sleep_quality between 1 and 5),
  created_at timestamptz not null default now()
);

create index if not exists sleep_logs_member_date_idx
  on public.sleep_logs (member_id, date desc, id desc);

alter table public.sleep_logs enable row level security;

drop policy if exists "sleep_logs_public_select" on public.sleep_logs;

drop policy if exists "sleep_logs_public_insert" on public.sleep_logs;
create policy "sleep_logs_public_insert"
  on public.sleep_logs for insert
  to anon
  with check (
    member_id ~ '^ycc[0-9]{8}$'
    and sleep_time_ampm in ('AM', 'PM')
    and headphone_min between 0 and 600
    and sleep_onset_min between 0 and 300
    and wakeup_count between 0 and 20
    and disturbance_scale between 0 and 5
    and sleep_quality between 1 and 5
  );

drop policy if exists "sleep_logs_public_delete" on public.sleep_logs;

grant usage on schema public to anon, authenticated;
revoke all on public.sleep_logs from anon, authenticated;
grant insert on public.sleep_logs to anon;
revoke all on sequence public.sleep_logs_id_seq from anon, authenticated;
grant usage, select on sequence public.sleep_logs_id_seq to anon;

-- If you import sleep_logs_rows.sql, run this afterwards so new IDs continue correctly:
-- select setval('public.sleep_logs_id_seq', coalesce((select max(id) from public.sleep_logs), 1), true);
